#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'PRE-TESTING COMMIT 🤞'

# ============================== FORMAT  ==============================
npm run format ||
(
    echo '❌ Format Failed ❌';
    false;
)

# ============================== check PRETTIER ==============================
npm run check-format ||
(
    echo '❌ Prettier check failed. (try to : npm run format) ❌';
    false;
)

# ============================== check ESLINT ==============================

npm run lint-fix ||
(
        echo '❌ ESLint check failed. ❌'
        false; 
)

# ============================== check TS CONFIG ==============================

npm run check-types ||
(
    echo '❌ TypeScript check failed. ❌'
    false;
)

# ============================== TRY TO BUILD ==============================

echo '🤔 Everything looks good. Try to npm run build 🤔'

# ============================== check RUN BUILD ==============================

# npm run build ||
# (
#     echo '❌🔨 run build failed ❌🔨'
#     false;
# )

# ============================== SUCCESS ==============================

echo '✅ Commit done with SUCCESS. ✅'